export const ROUTES = {
  BUSCA: '/busca',
  CADASTRAR_POST: '/post/cadastrar',
  EDITAR_POST: '/editar-post',
  COMENTARIOS_DE_POST: '/post/comentarios',
  EXIBIR_POST: '/post',
  AUTENTICACAO: '/autenticacao',
  EDITAR_PERFIL: '/editar-perfil',
  PERFIL: '/perfil',
  EDITAR_INTERESSES: '/editar-interesses',
  FEITOS: '/feitos',
  FAVORITOS: '/favoritos',
  SUAS_LISTAS: '/suas-listas',
  FILTRAGEM: '/filtragem',
  FILTRAGEM_RESULTADO: '/filtragem/resultado',
  EXIBIR_LISTA: '/lista',
  ADICIONAR_POST_LISTA: '/lista/adicionar-post',
  HOME: '/',
};
